######################################################################
#         Prj: Multi-omics data analysis of P.sibiricum.
#         Assignment: Visualize.
#         Date: Sep 24, 2022
#         Author: Shawn Wang <shawnwang2016@126.com>
#         Location: HENU, Kaifeng, Henan, China
#######################################################################

## load object
library(patchwork)
load("../Data_cleaning/NEG/raw/object.rds")
object_n_impute <- object
load("../Data_cleaning/POS/raw/object.rds")
object_p_impute <- object
load("../Data_cleaning/NEG/cleandata/object_neg.rds")
load("../Data_cleaning/POS/cleandata/object_pos.rds")
box_plt_batch = function(x,title) {
  x.order = x %>%
    extract_sample_info() %>%
    filter(group == "QC") %>%
    select(sample_id,injection.order) %>%
    arrange(injection.order) %>%
    pull(sample_id)
  box_plt <-
    x %>%
    extract_expression_data() %>%
    select(contains("QC")) %>%
    pivot_longer(contains("QC"),names_to = "sample",values_to = "peak") %>%
    mutate(peak = log10(peak+1),
           sample = factor(sample,levels = x.order)) %>%
    ggplot(.,aes(x = sample,y = peak,fill = sample)) + geom_boxplot(alpha = 0.6) +
    xlab("")+
    ylab("log10(peak area)")+
    ggtitle(title)+
    theme_bw()+
    theme(
      rect = element_rect(size = 1.5,color = 'black'),
      axis.title.y = element_text(size = 14,color = "black"),
      axis.text.x = element_text(size = 12,color = "black",angle = 90,vjust = .5,hjust = 1),
      axis.text.y = element_text(size = 12,color = "black"),
      title = element_text(size  = 15,colour = "black"),
      legend.position = "none"
    )
  return(box_plt)
}
n_before =
  object_n_impute %>% box_plt_batch(.,title = "negative before")
p_before =
  object_p_impute %>% box_plt_batch(.,title = "positive before")
n_after =
  object.neg %>% box_plt_batch(.,title = "negative after")
p_after =
  object.pos %>% box_plt_batch(.,title = "positive after")

figureS1 <-(p_before + p_after)/(n_before + n_after) + plot_annotation(tag_levels = "A")
ggsave(figureS1,filename = "../../../04.Result/02.Figures/FigS1.batch_effect_boxplot.png",width = 14,height = 7,dpi = 300)
ggsave(figureS1,filename = "../../../05.Report/FigS1.batch_effect_boxplot.png",width = 14,height = 7,dpi = 300)


library(PCAtools)

pos <- IMOtoolkits::IMO_plt_pca(obj = object.neg %>% activate_mass_dataset("expression_data") %>% drop_na(),tag = "group")

neg <- IMOtoolkits::IMO_plt_pca(obj = object.pos %>% activate_mass_dataset("expression_data") %>% drop_na(),tag = "group")

IMO_plt_rsd = function(obj_old,obj_new,QC_tag,x_loc = c(120,110),y_loc = c(15,110),interactive = F,showImage=T){
  # msg_yes = green$bold$italic
  # msg_no = red$bold$italic
  # msg_warning = yellow$bold$italic
  if (class(obj_old) != 'mass_dataset' | class(obj_new) != 'mass_dataset') {
    message(msg_no("error: Only obj which generated by massdataset accepted! Please check your input." ))
    return()
  }
  # calculate rsd for old object and new object.
  rsd_before <-
    obj_old %>%
    activate_mass_dataset("sample_info") %>%
    dplyr::filter(class == QC_tag) %>%
    extract_expression_data() %>%
    rownames_to_column("ID") %>%
    pivot_longer(contains(QC_tag),names_to = "tag",values_to = "value") %>%
    select(-tag) %>%
    group_by(ID) %>%
    summarise(
      raw.rsd = (sd(value,na.rm = T)/mean(value,na.rm = T))*100
    )
  rsd_after <-
    obj_new %>%
    activate_mass_dataset("sample_info") %>%
    dplyr::filter(class == QC_tag) %>%
    extract_expression_data() %>%
    rownames_to_column("ID") %>%
    pivot_longer(contains(QC_tag),names_to = "tag",values_to = "value") %>%
    select(-tag) %>%
    group_by(ID) %>%
    summarise(
      norm.rsd = (sd(value,na.rm = T)/mean(value,na.rm = T))*100
    )
  join_rsd <- inner_join(rsd_before,rsd_after,by = "ID") %>%
    mutate(
      norm_tag = case_when(
        norm.rsd <= 30 ~ "RSD ≤ 30",
        TRUE ~ "RSD > 30 "
      ),
      raw_tag = case_when(
        raw.rsd <= 30 ~ "RSD ≤ 30",
        TRUE ~ "RSD > 30 "
      )
    )
  #
  n1 = join_rsd %>% group_by(norm_tag) %>% summarise(num = n())

  rsd_plt = ggplot(data = join_rsd,mapping = aes(x = raw.rsd,y = norm.rsd,color = norm_tag)) +
    geom_point(size = 1.2,alpha =.8)+
    scale_color_manual(values = c("RSD ≤ 30" = "salmon","RSD > 30" = "grey30"))+
    geom_vline(xintercept = 30,linetype = "dashed",color = "red")+
    geom_hline(yintercept = 30,linetype = "dashed",color = "red")+
    geom_abline(slope = 1,linetype = "dashed",color = "red")+
    geom_label(
      data = data.frame(
        x = x_loc,
        y = y_loc,
        label = paste0("n=",c(n1[2,2],n1[1,2])),
        color = (c("RSD ≤ 30","RSD > 30"))
      ),
      mapping = aes(x = x,y = y,label = label,color= color),alpha = .8
    )+
    xlim(0,150)+
    ylim(0,150)+
    labs(x = "RSD of raw peak area",y = "RSD of svr normalized peak area")+
    theme_bw()+
    theme(
      line = element_line(size = 1.5,color = "black"),
      rect = element_rect(size = 1.5, color = "black"),
      axis.text = element_text(size = 14, color = "black"),
      axis.title = element_text(size = 14,color = "black")
    )
  if (isTRUE(showImage)) {
    print(rsd_plt)
  }
  out = list(
    rsd_tbl = join_rsd,
    plot = rsd_plt
  )
  return(out)
}

rsd_neg <- IMO_plt_rsd(
  obj_old = object_n_impute,
  obj_new = object.neg,QC_tag = "QC"
)

rsd_pos <- IMO_plt_rsd(
  obj_old = object_p_impute,
  obj_new = object.pos,QC_tag = "QC"
)



figureS2 <-
  (pos$plot+ neg$plot)/
  (rsd_pos$plot + rsd_neg$plot) + plot_annotation(tag_levels = "A")+ plot_layout(guides = "collect")&
  theme(legend.position =  'bottom',
        legend.title = element_blank())

ggsave(figureS2,filename = "../../../04.Result/02.Figures/FigS2.raw_data_pca.png",width = 14,height = 14,dpi = 300)
ggsave(figureS2,filename = "../05.Report/FigS2.raw_data_pca.png",width = 14,height = 14,dpi = 300)
